### ISSUE TITLE
Error while installing yolo34py-gpu

### ISSUE THREAD

**Issue by sushant1727** [madhawav/YOLO3-4-Py#11]
I am having this error when installing via:
pip3 install yolo34py-gpu

Collecting yolo34py-gpu' 'Downloading' 'https://files.pythonhosted.org/packages/dc/a3/12c668e54109c5469a8312d757b357dda0b2efc2150043b76b58f6ba75c3/yolo34py-gpu-0.1rc12.tar.gz (66kB)' ' 100% |################################| 71kB 1.1MB/s' ' Complete output from command python setup.py egg_info:' ' Traceback (most recent call last):' 'File "<string>", line 1, in <module>' 'File "C:\Users\Yuliia\AppData\Local\Temp\pip-install-v3jjunpq\yolo34py-gpu\setup.py", line 47, in <module>' ' if USE_CV & (get_libs("opencv") == '' or get_cflags("opencv") == ''):' 'File "C:\Users\Yuliia\AppData\Local\Temp\pip-install-v3jjunpq\yolo34py-gpu\util.py", line 85, in get_libs' ' proc = subprocess.Popen(shlex.split(command), stdout=subprocess.PIPE, stderr=subprocess.PIPE)' ' File "c:\program files\python 3.5\lib\subprocess.py", line 950, in __init__ restore_signals, start_new_session)' ' File "c:\program files\python 3.5\lib\subprocess.py", line 1220, in _execute_child startupinfo)' ' FileNotFoundError: [WinError 2] The system cannot find the file specified'

**Comment by sushant1727** [comment]
Using Opencv3.4.0 Python 3.5 Cuda 9.1

**Comment by madhawav** [comment]
Hi, unfortunately we do not support windows since Darknet, the core api wrapped here doesn't officially support Windows. I've found an alternative version of darknet which does work in windows (as mentioned in Windows support issue), but more work needs to be done to get the wrapper working with that. (its based on an earlier version of darknet which is somewhat different from what is wrapped by the wrapper)

I will update the issue on Windows support when windows support is added.

So closing the issue since Window support is currently not ready.
Cheers

**Comment by sushant1727** [comment]
Ok, I get it now.
(I get the same error when I run the above command in ubuntu16.04 though, any reason for that ?)
Thanks
