### ISSUE TITLE
How can I ignore the cat I don't want to detect.

### ISSUE THREAD

**Issue by sushant1727** [madhawav/YOLO3-4-Py#13]
I have trained my model using Darknet yolo-tiny model and I would like to ignore the objects I don't want to detect.
Is there a way to do that?

Also, is there a way to track the object after it is detected, any suggestion would be appreciated.

Thanks

**Comment by madhawav** [comment]
Hi, 
You can filter unwanted labels in results by post-processing results like below.
```python
            exclusions = ["cat"]
            results = net.detect(dark_frame)
            results = [r for r in results if r[0] not in exclusions]
```

The labels in exclusions list will be removed from results.

Regarding object tracking, You can try out the trackers available with OpenCV.
This tutorial should be a good starting point - https://www.learnopencv.com/object-tracking-using-opencv-cpp-python/.

PS- You will need to have opencv installed with contrib modules in order to use trackers.

**Comment by sushant1727** [comment]
You're awesome thanks for all the suggestions.

**Comment by madhawav** [comment]
@sushant1727 That would require tracking of cats. You can get the idea from following tutorial.
https://www.learnopencv.com/object-tracking-using-opencv-cpp-python/
