### ISSUE TITLE
Getting Error In Ubuntu "x86_64-linux-gnu-gcc: error: pydarknet.cpp: No such file or directory"

### ISSUE THREAD

**Issue by shivarajnaidu** [madhawav/YOLO3-4-Py#27]
When I run the command `python setup.py build_ext --inplace`
```
x86_64-linux-gnu-gcc: error: pydarknet.cpp: No such file or directory
```

![image](https://user-images.githubusercontent.com/12374494/44156397-641d97ac-a0cd-11e8-8ee6-255699f0718f.png)

**Comment by madhawav** [comment]
Hi, do you have cython installed?
If not, please install cython using `pip install cython`. Cython is used by setup.py to generate pydarknet.cpp.

**Comment by madhawav** [comment]
Hi, 
Can you test whether the following import works?
```python
  from Cython.Distutils import build_ext
```
To explain the situation, pydarknet.cpp is generated using Cython. If the above import fails (which usually happen when cython is absent), the installation assumes pydarknet.cpp already exists and tries to install using it. This seem to be the case according to log you have provided since it contains no logs generated by cython. 

Also, can you try making a new clone of the project? Sometimes, cython leaves partly compiled files that can cause weird issues.

**Comment by madhawav** [comment]
Closing the issue due to two weeks of inactivity.

**Comment by suraj-pai** [comment]
I was able to fix this by installing python3-dev package

```
sudo apt install python3-dev
```
