### ISSUE TITLE
How could I modify the docker run file to get the GPU enabled version of Yolov3 running?

### ISSUE THREAD

**Issue by LukeAI** [madhawav/YOLO3-4-Py#52]
How could I modify the docker run file to get the GPU enabled version of Yolov3 running in a docker?

**Comment by madhawav** [comment]
I have added a [Dockerfile](https://github.com/madhawav/YOLO3-4-Py/blob/master/docker/Dockerfile-gpu) to support nvidia-docker. 
Follow the instructions in "How to run demo using docker?" section of the readme. (use [run-gpu.sh](https://github.com/madhawav/YOLO3-4-Py/blob/master/docker/run-gpu.sh) instead of run.sh)
